# Generated by Django 6.0 on 2025-12-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(max_length=20)),
                ('meaning', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('sound', models.FileField(upload_to='')),
                ('phonetic', models.CharField(max_length=100)),
                ('vocab_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabset')),
            ],
        ),
    ]
