# Generated by Django 6.0 on 2025-12-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='meaning',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='phonetic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='vocab',
            field=models.CharField(max_length=200),
        ),
    ]
