# Generated by Django 6.0 on 2025-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_alter_vocab_meaning_alter_vocab_phonetic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/pictures'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='sound',
            field=models.FileField(blank=True, upload_to='media/sounds'),
        ),
    ]
