# Generated by Django 6.0 on 2025-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_alter_vocab_picture_alter_vocab_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='sound',
            field=models.FileField(blank=True, upload_to='sounds'),
        ),
    ]
