# Generated by Django 6.0 on 2025-12-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='choices',
            field=models.JSONField(default=list),
        ),
    ]
